 var gf_map_mod_1 = new clsGfMap();
function initialiseGfCarte() {
gf_map_mod_1.imageGalWait= 'http://qiches.com/components/com_geocode_factory/assets/images/icon_wait.gif' ; 
gf_map_mod_1.imageGalClose= 'http://qiches.com/components/com_geocode_factory/assets/images/lightbox-btn-close.gif' ;
gf_map_mod_1.imageGalPrev= 'http://qiches.com/components/com_geocode_factory/assets/images/lightbox-btn-prev.gif' ;
gf_map_mod_1.imageGalNext= 'http://qiches.com/components/com_geocode_factory/assets/images/lightbox-btn-next.gif' ;
gf_map_mod_1.imageShadow= 'http://qiches.com/components/com_geocode_factory/assets/images/marker_avatar.gif' ;
gf_map_mod_1.setIconMyPos('http://qiches.com/components/com_geocode_factory/assets/images/locate_me.gif') ;
gf_map_mod_1.iconeUser1= 'http://qiches.com/components/com_geocode_factory/assets/images/address_1.png' ;
gf_map_mod_1.iconeUser2= 'http://qiches.com/components/com_geocode_factory/assets/images/address_2.png' ;
gf_map_mod_1.iconeUser3= 'http://qiches.com/components/com_geocode_factory/assets/images/address_3.png' ;
gf_map_mod_1.imageWait= '<img src="'+ gf_map_mod_1.imageGalWait +'" />'; 
gf_map_mod_1.rootJoomla= '/index.php'; 
gf_map_mod_1.idsNoStreetView = "There is no streetview available here." ;
gf_map_mod_1.setCenterPointDefault(38.3456, 113.6754);
gf_map_mod_1.setMMZ(2,15); 
gf_map_mod_1.setMTB('ROADMAP', 1, 'DROPDOWN_MENU'); 
gf_map_mod_1.setDWZ(1, 1); 
gf_map_mod_1.setMZC(10); 
gf_map_mod_1.setSMC('0'); 
gf_map_mod_1.setCTRL('1','1', '1', '1'); 
gf_map_mod_1.createMap('gf_map_mod_1'); 
gf_map_mod_1.autoCompleteStart('', 0); 
gf_map_mod_1.addNote(); 
gf_map_mod_1.setMouse(0, 1,0, 1); 
gf_map_mod_1.initCluster(5, 60, '', [], 1); 
gf_map_mod_1.setUseRoutePlaner() ; 
var layersCtrls = [] ;var sep = new separator();
layersCtrls.push( new checkBox({gmap: gf_map_mod_1.map, title: "Transit" , id: "transit", label: "Transit" }) ); 
 layersCtrls.push( sep );
layersCtrls.push( new optionDiv({ gmap: gf_map_mod_1.map, name: "Hide all",title: "Hide all", id: "mapOpt"}) ); 
var ddDivOptions = {items: layersCtrls ,id: "myddOptsDiv"};
var dropDownDiv = new dropDownOptionsDiv(ddDivOptions); 
var dropDownOptions = {gmap: gf_map_mod_1.map, name: "More...", id: "ddControl", title: "Show/hide layers", position: google.maps.ControlPosition.TOP_RIGHT, dropDown: dropDownDiv};
var dropDown1 = new dropDownControl(dropDownOptions);
gf_map_mod_1.nameDebugCont = 'null' ; 
gf_map_mod_1.xmlFileDyn = '/index.php?option=com_geocode_factory&task=getXmlInfoFromDbByIdMap&idMap=1&Itemid=&code=38840' ; 
gf_map_mod_1.setXmlFile('/index.php?option=com_geocode_factory&task=getXmlInfoFromDbByIdMap&idMap=1&Itemid=&code=38840'); 
gf_map_mod_1.drawRadiusCircle = true; 
gf_map_mod_1.setColorpline(['','','','','','','','','','','','']); 
gf_map_mod_1.useBoundary = true ; 
gf_map_mod_1.manageMapClick(1); 
gf_map_mod_1.useTabs=true; 
gf_map_mod_1.getBrowserPos(false, true);
}
google.maps.event.addDomListener(window, 'load', initialiseGfCarte);
